### ISSUE TITLE
Build for Fedora 41 and rawhide

### ISSUE THREAD

**Issue by yorickpeterse** [daobrien/vale-spec#2]
The [Copr project](https://copr.fedorainfracloud.org/coprs/mczernek/vale) is missing builds for Fedora 41 and Rawhide. Would it be possible to add a build for both, such that for future releases Vale is available automatically? Thanks!

**Comment by yorickpeterse** [comment]
@daobrien I don't mean to be pushy, but is there any indication as to if/when the Copr project will provide builds for Fedora 41? Thanks! :smiley:

**Comment by daobrien** [comment]
> @daobrien I don't mean to be pushy, but is there any indication as to if/when the Copr project will provide builds for Fedora 41? Thanks! 😃

Not being pushy at all. I've been overseas for the last two weeks and just saw this. I'll get onto it. Thanks for keeping me on my toes :)

**Comment by daobrien** [comment]
F41 should  be available now. Is there any particular reason you wanted rawhide? Personally I've never built anything for rawhide and I'm not sure I want to start on that path.

**Comment by yorickpeterse** [comment]
@daobrien Thanks! 

> F41 should be available now. Is there any particular reason you wanted rawhide? Personally I've never built anything for rawhide and I'm not sure I want to start on that path.

It's not because I use Rawhide itself, but rather because when a build is added for Rawhide it's automatically branched to a new release when those are published. So when Fedora 42 is released, a build/job/whatever is automatically created for it, removing the need for manual intervention every six months :smiley:

**Comment by yorickpeterse** [comment]
Oh, I just checked the Copr project and it seems that while Fedora 41 was added, it wasn't used for the build https://copr.fedorainfracloud.org/coprs/mczernek/vale/build/8274882/. Perhaps the build was triggered before adding Fedora 41?

**Comment by daobrien** [comment]
For some reason the 41 build is failing. I've got my hands full right now but will try to look at it very soon. The F40 build should work afaik. Apologies for the hiccup.

**Comment by yorickpeterse** [comment]
@daobrien No worries! I'll take a look at the spec tonight to see what changes are needed to get it to build on Fedora 41, then I'll set up a PR if I figure things out :smile:

**Comment by daobrien** [comment]
> @daobrien No worries! I'll take a look at the spec tonight to see what changes are needed to get it to build on Fedora 41, then I'll set up a PR if I figure things out 😄

I have a revised spec file from someone on the Fedora Build page which I'm hoping will fix this. I'm pretty snowed right now but will try to get it in place later today.

**Comment by daobrien** [comment]
@yorickpeterse This should work now. I've just tested it on my F41 VM.

**Comment by yorickpeterse** [comment]
@daobrien Thanks!
